### ISSUE TITLE
CloudEvent module seems to be useless

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-rust#100]
It is unclear what the CloudEvent module's functionality would be useful for.
All uProtocol APIs revolve around UMessages and it is up to a transport implementation if it wants to map UMessages to CloudEvents when writing the messages to the transport PDUs.

The code is also pretty much unmaintainable with the hundreds of verbatim unit tests ...

I propose to simply remove the module and add something more suitable once we see the need for it.

@AnotherDaniel @stevenhartley WDYT?

**Comment by AnotherDaniel** [comment]
Agree - there's the aspect of this being a mostly mindless (on my part) port of what I found elsewhere - at a time when cloudevent was more relevant than it is today. Also, current experience tells me that what currently exists in up-rust might not always be exactly what's really needed from uE implementation side.

So I'd say remove this bit - and if we need cloudevend-related functionality in the future, we should probably create a dedicated up-rust-cloudevent crate...

**Comment by stevenhartley** [comment]
Only up-java will need to maintain the cloudevent support for now so we can provide backwards compatibility between 1.3.6 and 1.5.x so you can remove it from up-rust
