### ISSUE TITLE
Throw out map_response() and map_response_to_result() from RpcMapper?

### ISSUE THREAD

**Issue by AnotherDaniel** [eclipse-uprotocol/up-rust#106]
Hi especially @PLeVasseur and @evshary - question: doing my usubscription thing, I've come to the point where I found out what kind of functionality I need from RpcMapper around using `invoke_method()`, and the current `map_response()` and `map_response_to_result()` are essentially useless from my PoV.

I have more pragmatic alternatives in the pipeline, but would like to remove the current map_response code along with that. 
 
So my question is, are you using `RpcMapper::map_response()` and  `RpcMapper::map_response_to_result()` anywhere in your code?

**Comment by evshary** [comment]
Nope on my side, either.

**Comment by AnotherDaniel** [comment]
Done
