### ISSUE TITLE
Protobuf minimum unsigned integer (u32) vs UResource & UEntity id size (u16)

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-rust#11]
Hi there :wave:

I noticed when serializing the UURI to micro form, we do some bit shifts and casting to get the desired 16 bits written for the UResource and UEntity ids.

I suppose it's possible based on what I see [here](https://github.com/eclipse-uprotocol/uprotocol-rust/blob/50b3a7b5d932b351f338518c2e1b7886e9c2da01/src/uri/serializer/microuriserializer.rs#L111-L112) and [here](https://github.com/eclipse-uprotocol/uprotocol-rust/blob/50b3a7b5d932b351f338518c2e1b7886e9c2da01/src/uri/serializer/microuriserializer.rs#L117-L118) that we could form ids which are larger than the allotted 16 bits when serializing.

Perhaps we should explicitly check to make sure we can fit the ids within the allotted bits, e.g.
```rust
const UENTITY_ID_LENGTH: usize = 16;
const UENTITY_ID_VALID_BITMASK: u32 = 0xffff << UENTITY_ID_LENGTH;
const URESOURCE_ID_LENGTH: usize = 16;
const URESOURCE_ID_VALID_BITMASK: u32 = 0xffff << URESOURCE_ID_LENGTH;
// ...
        // URESOURCE_ID
        if let Some(id) = uri.resource.as_ref().and_then(|resource| resource.id) {
            // this is new -- start
            if id & URESOURCE_ID_VALID_BITMASK != 0 {
                return Err(SerializationError::new(format!("UResource id larger than allotted 16 bits: 0x{:x}", id)));
            }
            // this is new -- end
            cursor.write_all(&[(id >> 8) as u8]).unwrap();
            cursor.write_all(&[id as u8]).unwrap();
        }

        // UENTITY_ID
        if let Some(id) = uri.entity.as_ref().and_then(|entity| entity.id) {
            // this is new -- start
            if id & UENTITY_ID_VALID_BITMASK != 0 {
                return Err(SerializationError::new(format!("UEntity id larger than allotted 16 bits: 0x{:x}", id)));
            }
            // this is new -- end
            cursor.write_all(&[(id >> 8) as u8]).unwrap();
            cursor.write_all(&[id as u8]).unwrap();
        }
```

And these are the accompanying tests which pass with the code changes above:
```rust
    #[test]
    fn test_uentity_id_greater_than_16_bits() {
        let uri = UUri {
            entity: Some(UEntity {
                id: Some(1 << UENTITY_ID_LENGTH),
                version_major: Some(254),
                ..Default::default()
            }),
            resource: Some(UResource {
                id: Some(19999),
                ..Default::default()
            }),
            ..Default::default()
        };

        let uprotocol_uri = MicroUriSerializer::serialize(&uri);
        assert!(uprotocol_uri.is_err());
        assert_eq!(
            uprotocol_uri.unwrap_err().to_string(),
            "UEntity id larger than allotted 16 bits: 0x10000"
        );
    }

    #[test]
    fn test_uresource_id_greater_than_16_bits() {
        let uri = UUri {
            entity: Some(UEntity {
                id: Some(29999),
                version_major: Some(254),
                ..Default::default()
            }),
            resource: Some(UResource {
                id: Some(1 << URESOURCE_ID_LENGTH),
                ..Default::default()
            }),
            ..Default::default()
        };

        let uprotocol_uri = MicroUriSerializer::serialize(&uri);
        assert!(uprotocol_uri.is_err());
        assert_eq!(
            uprotocol_uri.unwrap_err().to_string(),
            "UResource id larger than allotted 16 bits: 0x10000"
        );
    }
```

Perhaps a more thorough solution is to create some sort of internal-to-the-Rust-library version of the UURI that can ensure that this does not occur in the first place? But I'm not familiar enough yet to have found other instances like this.

**Comment by PLeVasseur** [comment]
After reading a bit more through the spec for URIs and uSubscription, I am kinda considering some way to "front load" some of the verification and safety with some sort of builder for URIs.

I'm still thinking about how that might look. Might post some skeleton here later.

**Comment by PLeVasseur** [comment]
Okay, I'm looking at this again and reading the spec [specifically this part](https://github.com/eclipse-uprotocol/uprotocol-spec/blob/0367babc291968effade94ee093e35641e7c84be/basics/uri.adoc#L281:~:text=All%20fields%20of%20micro%20UUri%20MUST%20be%20populated):
> All fields of micro UUri MUST be populated

Does that mean if the UEntity id or UResource id are empty we should fail to serialize? i.e. return a `SerializationError`?

Tagging in @stevenhartley, @sophokles73 for some guidance.

**Comment by sophokles73** [comment]
> Does that mean if the UEntity id or UResource id are empty or overflow 16 bits we should fail to serialize? i.e. return a SerializationError?

That is my understanding.

**Comment by stevenhartley** [comment]
Not sure what you mean by "empty", Entity Id of 0 is the uSubscription service and resource id of 0 is the fixed rpc.response topic

**Comment by PLeVasseur** [comment]
Yup, you're right. My bad.
