### ISSUE TITLE
Docs.rs cannot build up-rust documentation

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-rust#159]
Docs.rs has failed to build the documentation for [up-rust](https://docs.rs/crate/up-rust/0.1.1/builds) because it does not allow any network access as part of the build.
However, the up-rust build currently downloads the uProtocol proto3 files as part of the build process :-(

**Comment by sophokles73** [comment]
Here's the [issue I had opened for this](https://github.com/rust-lang/docs.rs/issues/2558)

**Comment by sophokles73** [comment]
We deliberately chose to not copy the proto3 files manually into the up-rust code base.
Alternatively, we could use a git submodule to include the proto3 files referring to the latest tag in the up-spec repository.
We originally wanted to retrieve the proto3 files from the _main_ branch of up-spec in order to see if anything brakes in our code when running the nightly build. I guess we could still do that if we explicitly set/override the branch/tag to use for checking out the submodule in the nightly build.

WDYT? @evshary @AnotherDaniel @PLeVasseur

**Comment by AnotherDaniel** [comment]
Damn, I really liked the way we handled the proto files so far. Unobstrusive, transient, always works.

But I guess submodules are the only viable option then? With that nightly-build twist you mention...

**Comment by sophokles73** [comment]
My understanding is that docs.rs uses the sources that are published on crates.io. They do not check out the code from GitHub at all. So, if we include the proto3 files in the release process, then we should be fine (:crossed_fingers:)

**Comment by AnotherDaniel** [comment]
Ok.

**Comment by sophokles73** [comment]
If what I say is true, then we might be able to cleverly copy the proto3 files into the right place as part of the release build, of course ...

**Comment by sophokles73** [comment]
we could then conditionally download the proto3 files only when _not_ building on docs.rs (which we can easily determine by means of an [environment variable](https://docs.rs/about/builds#detecting-docsrs)).

**Comment by sophokles73** [comment]
On the other hand, a git submodule would actually do all that is necessary _for free_ ...

**Comment by AnotherDaniel** [comment]
Yeah - and I have the feeling that it will be highly hacky to try and copy files from the target directory into the regular workspace scope...

**Comment by sophokles73** [comment]
ok, I will start doing some experiments with using a submodule ...

**Comment by PLeVasseur** [comment]
Echoing @AnotherDaniel. I really liked the setup we had, to tell immediately when an upstream up-core-api change broke the build.

Appreciate your experiments @sophokles73

**Comment by sophokles73** [comment]
closed via #160
