### ISSUE TITLE
The combination of resource ID of source and sink

### ISSUE THREAD

**Issue by evshary** [eclipse-uprotocol/up-rust#166]
When I'm using the L2 API, I found that `InMemoryRpcServer` call `register_listener` with source UUri `UUri::any()`, which means `//*/FFFF/FF/FFFF`.
https://github.com/eclipse-uprotocol/up-rust/blob/8a9fe59882c9ad67a63c7a3a052d37a5017082e2/src/communication/in_memory_rpc_server.rs#L232

I created a table [here](https://github.com/eclipse-uprotocol/up-spec/tree/main/up-l1#23-registerlistener) before to list all the combinations of resource ID for `register_listener`.
![image](https://github.com/user-attachments/assets/5dd318c8-773c-449e-b5c3-ad4a3187201a)
The reason I removed `source resource_id=FFFF & sink resource_id=[1-7FFF]` is that the source resource_id should always be 0 here. However, I agree that in the L2 API case, it might be annoying for users to use `//*/FFFF/FF/0` as the source Uri.

Furthermore, if we decided to add back the combination of `{FFFF, 1-7FFF}`, then it will come across [the question I met before](https://github.com/eclipse-uprotocol/up-spec/pull/188#discussion_r1673355607). Should we also add back the other cases?

@sophokles73 WDYT?

**Comment by sophokles73** [comment]
I agree that in line 232 we should use `//*/FFFF/FF/0` as the origin filter if not specified explicitly by the user.

**Comment by sophokles73** [comment]
Would you like to create a PR?
