### ISSUE TITLE
Expose MockTransport for use in other repositories

### ISSUE THREAD

**Issue by matthewd0123** [eclipse-uprotocol/up-rust#185]
Hello,

I've been working on up-streamer-rust, and in the course of writing some tests, I found the need to mock some uTransports to test error conditions. I saw MockTransport in https://github.com/eclipse-uprotocol/up-rust/blob/main/src/utransport.rs and think it would be very useful to have in that repo, so am proposing to make that a pub. If that's acceptable, I will make the PR for it.

**Comment by sophokles73** [comment]
A PR would be very welcome :-)
I would suggest to make it conditional on either the `test` or `util` profile then ...

**Comment by sophokles73** [comment]
closed via #213
