### ISSUE TITLE
Did we remove the validation for ue_version_major and resource_id being the correct number of bits?

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-rust#209]
I was looking to use this today and seems like it was not migrated over when we had core API changes a while back.

I see in [here](https://github.com/eclipse-uprotocol/up-rust/commit/57c3c8c1b69880e469529424431cc3805b006576#diff-c268be64cebcd98764bc192af60854a8ae20ec005a47cd379314f36b6f0cc57a) @sophokles73 seems to have removed (?) the concept of validating the length of bits contained in the `ue_version_major` and `resource_id`.

Maybe I'm missing something though?

I like how [`UUri::try_from_parts`](https://github.com/eclipse-uprotocol/up-rust/blob/614e73aae8b78bdd14c09449dc8bbe898c5ace6d/src/uri.rs#L369) will give us a correct-by-construction `UUri`, but I'd like the ability to verify that a `UUri` that I'm given matches the correct specification [here](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/uri.adoc#2-data-model).

Perhaps we removed the ability to check this?

Can I get a sanity check here before I reimplement this?

**Comment by sophokles73** [comment]
Hmm, when parsing a UUri from a URI string we do check that it is an 8 bit unsigned integer. But when we serialize to a URI string we do not. I guess you are right in that we should check there too. Is that what you are concerned about?

**Comment by PLeVasseur** [comment]
Yeah, validating a `UUri` that's of unknown provenance is what I was getting at. I think you've understood my ask and are working to implement the ability to do that in #210.
