### ISSUE TITLE
Question about UUID

### ISSUE THREAD

**Issue by evshary** [eclipse-uprotocol/up-rust#21]
While implementing ULink library, I found some weird behaviors on validating UUID.
After some tracing, I'm not quite sure about the implementation here. It seems like it doesn't correspond to protocol-spec.
https://github.com/eclipse-uprotocol/uprotocol-rust/blob/main/src/proto/uprotocol/uuid.rs#L77

To be more specific, my questions are
1. Why do we need to check the version is Version::Custom here?
2. Is there any expected way to generate UUID that can pass `is_uprotocol_uuid`?

**Comment by stevenhartley** [comment]
1. Older versions of the protocol used v6 so for Java we had to support both, for Rust I think you're safe to be v8 (platforms are being updated now to support v8 using the newer sdks)
2. You cannot build it with rust SDK but if you are passed a different format UUID you need to make sure it is formatted correctly per the spec.

**Comment by AnotherDaniel** [comment]
> 2\. Is there any expected way to generate UUID that can pass `is_uprotocol_uuid`?

Hi @evshary , do you mean that sentence exactly like that? If yes, the expected way to generate such a UUID is the uuidbuilder.rs/UUIDv8Builder. In case there is a 'not' missing from your question, Steven answered that in his comment ;-)

**Comment by evshary** [comment]
> Hi @evshary , do you mean that sentence exactly like that? If yes, the expected way to generate such a UUID is the uuidbuilder.rs/UUIDv8Builder. In case there is a 'not' missing from your question, Steven answered that in his comment ;-)

Thanks! That's exactly what I want.
Although I still don't quite understand how `is_uprotocol_uuid` works (why do we need to compare the version of UUID with `Version::Custom`), I think the information is enough for me to continue the project.
