### ISSUE TITLE
Provide a way to get entity type from UUri

### ISSUE THREAD

**Issue by evshary** [eclipse-uprotocol/up-rust#219]
Just as we discussed here https://github.com/eclipse-uprotocol/up-transport-zenoh-rust/pull/93#discussion_r1867312701, it would be convenient if we could provide a function for transport layers to get the entity type from UUri.

**Comment by sophokles73** [comment]
Can you elaborate a little regarding what you would expect to get, e.g. by means of an example?

**Comment by evshary** [comment]
> Can you elaborate a little regarding what you would expect to get, e.g. by means of an example?

Perhaps something like `uri.get_entity_type()`, which will return u16.
For example if `ue_id` in `uri` is `0x12345678`, it will return `0x5678`.
