### ISSUE TITLE
Marking UTransport, RpcServer, RpcClient traits as Send + Sync to ensure they are thread-safe

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-rust#24]
In beginning work on the uStreamer, I found the need to be able to put a `ULinkZenoh` struct inside an `Arc` to move it around in a thread safe manner and use a single instance of it.

However, I found that in order to do so I needed to add `Send` + `Sync` as required bounds on `UTransport`, `RpcServer`, and `RpcClient`.

Thankfully, the implementation of `up-client-zenoh-rust` was already written in a thread-safe manner, so I was able to fork `up-rust`, [make that small change](https://github.com/PLeVasseur/uprotocol-rust_fork/tree/feature/experiment_send_sync) and keep working for now.

I would like to codify that on those traits tho, once [the PR from CY](https://github.com/eclipse-uprotocol/up-rust/pull/22) merges which contains `RpcServer`.

WDYT @sophokles73, @AnotherDaniel, @evshary?

Perhaps we can also briefly discuss in tomorrow's meeting too.

**Comment by evshary** [comment]
Hi @PLeVasseur 
Since `UPClientZenoh` has already had Send + Sync, maybe you can use `Arc` without issues in a thread-safe manner.
Here is an example:
https://github.com/ZettaScaleLabs/up-client-zenoh-rust/blob/5faef31/examples/rpc_server.rs#L30
Let me know if I misunderstood your problem.

**Comment by PLeVasseur** [comment]
Hey @evshary -- thanks for pointing it out. The problem is using the trait objects `UTransport`, `RpcClient`, and `RpcServer` in a thread-safe manner. I ended up figuring out how to do so for now thanks to the nudge from @sophokles73 :+1: 

I think I can close this one for now.
