### ISSUE TITLE
Reorg and cleanup of source structure

### ISSUE THREAD

**Issue by AnotherDaniel** [eclipse-uprotocol/up-rust#31]
Hi fellow up-rustaceans, 
I want to do some fundamental cleanup and reorg of the SDK source file structure. Lining out the planned changes here, for feedback and also so we can maybe agree on a hands-off period for a week or so, where I then do all of this without making merging of parallel work more nightmarish than it needs to be.

The core things I want to do: 

- clean out the src/proto folder (this is there for 'historical reasons', but the introduction of up-core-api was the final nail in the coffin for the original idea)
- make the cloudevents bits an optional crate feature 

More detailed, I'm planning to do the following moves:

- the top-level uprotocol logic (mostly in /proto and the \*/datamodel folders atm) into the top-level /src folder
- the /uuid, /uri etc folders will remain, but contain the trait definitions for their associated types (validators, serializers etc)
- /rpc stays as it is
- /types only contains error definitions at this point, these well me merged and moved to top-level

__Note__: the external interface of the up-rust crate wouldn't change, so for users this should be transparent (with the possible exception of the cloudevents feature becoming optional, which I'd put into it's own PR though)

Any comments? Do any of you have some large changes in the pipeline that this should be time-synced with? Otherwise, I'd wait for the current batch of PRs to get merged, then pull of the above changes, then everyone could get back to work.

**Comment by PLeVasseur** [comment]
> * make the cloudevents bits an optional crate feature

I like this idea a lot :heart_eyes: 

> Otherwise, I'd wait for the current batch of PRs to get merged, then pull of the above changes, then everyone could get back to work.

Sounds good to me. I just have the one PR related to to Micro Form Uri that's there.

There's another PR I am working on to add the ability to compile & use `up-rust` as an Android module, but this will take time and I don't think it needs to block your work.

**Comment by AnotherDaniel** [comment]
Update: as soon as #54 and #52 are merged, I'll do the big file-move as described above.

**Comment by AnotherDaniel** [comment]
Starting the big shuffle now...

@sophokles73 @evshary @PLeVasseur contrary to what I thought initially, I'm beginning to think I'd like to change the external crate interface, basic simplifications like:

```use up_rust::uprotocol::uri::SerializationError;```

becomes

```use up_rust::uri::SerializationError;```


Would you kill me if I did a bit of that?

**Comment by sophokles73** [comment]
I wouldn't :-)

**Comment by PLeVasseur** [comment]
Makes sense to me =^)

**Comment by AnotherDaniel** [comment]
Hi all up-rustaceans - the Big Shuffle is done, #56 has been merged. As I've hinted at above, there have been changes to the user-facing API after all:

- every type is now directly available on crate top level, e.g. `use up_rust::UMessage;`
- there was a substantial re-design of Errors types; the upshot
	- modules that use Errors now individually declare and own them, which means we don't have blanket "SerializationError" any more, but e.g. `UUriError`
	- there is only one module-level Error type, e.g. `UUriError`, `UAttributesError`, and so on - but these are enums subsuming more specific error conditions; so what used to be "up_rust::uri::SerializationError" is now `up_rust::UUriError::SerializationError' 

Those are the major changes visible outside - I do apologize for imposing these changes on you and for the volume of changes, but I think the rework was worth it overall. And better do this now with 2-3 impacted persons[^1], than a year from now... 

[^1]: As long as it's just you three, I vow to make it up to you by means of a beer on my tab at the next opportunity ;-)

**Comment by AnotherDaniel** [comment]
Update: next stage of this issue is #61, which is about making certain features of up-rust optional:

- cloudevents and related dependencies
- up-l3 uDiscovery protobuf-generated code
- up-l3 uSubscription protobuf-generated code
- up-l3 uTwin protobuf-generated code

**Comment by AnotherDaniel** [comment]
Alright everyone - #61 has just been merged, which concludes the scope of improvements I aimed for with this issue.

There is a lot more to be done - for example:

- #51 is next, I will soon detail my collected thoughts in that issue for your feedback
- the entire cloudevents module needs streamlining and cleanup
- at least 2/3s of the unit tests we have need refactoring and cleanup

But build/release pipeline is next, so continue the conversation in that space.
