### ISSUE TITLE
Continuously check 3rd party dependency license compatibility

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-rust#39]
The Eclipse Foundation's development process requires us to make sure that the license terms of all 3rd party dependencies are compatible with the project's license (ASL2).

The first step in doing so is to actually determine the licenses that the 3rd party dependencies are using.

**Comment by AnotherDaniel** [comment]
Question: how about we use `cargo-deny` for this, as a 'first line of defense' check that can be part of our direct build pipe? I know Eclipse has some larger system, which also will want to be satisfied - but I'm thinking that `cargo-deny` is a very nifty helper for a Rust project, for this kind of thing.

**Comment by sophokles73** [comment]
closed via #25
