### ISSUE TITLE
Replace UAttributesBuilder with UMessageBuilder

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-rust#43]
With the changes introduced to `UTransport::send`, it seems more desirable to be able to easily build a `UMessage` to be sent instead of creating `UAttributes`.

**Comment by PLeVasseur** [comment]
Makes sense. Doing this for the different types of `UMessageType`, right? (Request, Response, Publish...) And we'd also pass in the `UPayload` to the builder?

**Comment by sophokles73** [comment]
Exactly

**Comment by sophokles73** [comment]
Closed via #46
