### ISSUE TITLE
Generate uAttributes in invoke_method

### ISSUE THREAD

**Issue by evshary** [eclipse-uprotocol/up-rust#47]
Now the definition of `invoke_method` is
```rust
async fn invoke_method(
        &self,
        method: UUri,
        request: UPayload,
        options: CallOptions,
    ) -> RpcClientResult;
```
https://github.com/eclipse-uprotocol/up-rust/blob/main/src/rpc/rpcclient.rs#L45C5-L50C26
While the structure of `CallOptions` is
```rust
pub struct CallOptions {
    timeout: u32,
    token: String,
}
``` 
https://github.com/eclipse-uprotocol/up-rust/blob/main/src/rpc/calloptions.rs#L18C1-L21C2

However, `invoke_method` is up-l2 API and it should be implemented by up-l1 API, which is `async fn send(&self, message: UMessage) -> Result<(), UStatus>;`
https://github.com/eclipse-uprotocol/up-rust/blob/main/src/transport/datamodel/utransport.rs#L42C5-L42C68

While UMessage comprises `uPayload` and `uAttributes`, does that mean we should generate our own `uAttributes` in `invoke_method`?

**Comment by stevenhartley** [comment]
We discussed this during the call this morning and example of this can be see in https://github.com/eclipse-uprotocol/up-client-android-java/blob/main/library/src/main/java/org/eclipse/uprotocol/UPClient.java#L668[UPClient.java]

**Comment by evshary** [comment]
Thanks @stevenhartley 
It's well explained and I'll close the issue.

**Comment by stevenhartley** [comment]
Good morning :-)
