### ISSUE TITLE
register/unregiter listener: register takes callback function as input but unregister requires string. Other sdk's take callback function as input for both register and unregister listner

### ISSUE THREAD

**Issue by sagarsshah** [eclipse-uprotocol/up-rust#65]
I wanted to discuss a potential overhead  to our rust SDK's listener apis. Currently, the register_listener() function within the SDK requires a listener parameter of type Box<dyn Fn(Result<UMessage, UStatus>) + Send + Sync + 'static>, returning a listener string for later use with unregister_listener().
However, I've found it challenging to manage listeners effectively without associating them directly with a UUri and associated function. Other SDKs like Java and Python, which accept the listener function directly for both registration and unregistration, our current Rust SDK requires additional bookkeeping to track listeners.
 
Though in real life scenario same uE will rarely listen twice on same UUri but still this can be good correction. Either we expose functions to convert listener function to listener string to uE developer OR we modify rust SDK to match other SDKs.

**Comment by PLeVasseur** [comment]
Hey @sagarsshah :wave:

Thanks for your feedback. I'll make a strawman proposal PR for us to all look at.

**Comment by PLeVasseur** [comment]
Hi @sagarsshah -- check out the draft PR here: #67

**Comment by PLeVasseur** [comment]
I took a different approach over in #68 that is a lot cleaner.

**Comment by PLeVasseur** [comment]
Latest attempt is in #69, using _instance equality_ instead of _type-level equality_ to align with what `up-client-android-java` is doing (and honestly, which makes more sense).

**Comment by sagarsshah** [comment]
Thanks. let me try #69 .

**Comment by sagarsshah** [comment]
I found integration to be very convenient, although I haven't tested it yet. I'll soon share my up-rust-socket code with you for your preview. Thanks.

**Comment by PLeVasseur** [comment]
Hey @sagarsshah -- we still need to get #69 reviewed before I want you to go to far in using it :slightly_smiling_face: 

Let's wait a little longer on others to review the PR

**Comment by PLeVasseur** [comment]
Hey again @sagarsshah -- this was implemented in #69.

Could you close the issue?

**Comment by sagarsshah** [comment]
I've completed the integration with my rust socket transport, and it seems to be ok. However, I still need to conduct testing to ensure everything is working as expected. hopefully by this weekend I will close this issue.

**Comment by PLeVasseur** [comment]
> I've completed the integration with my rust socket transport, and it seems to be ok. However, I still need to conduct testing to ensure everything is working as expected. hopefully by this weekend I will close this issue.

I think this issue regarding adding the functionality requested could be closed if #69 meets your needs.

If you have another issue (bug or missing functionality) uncovered when testing `up-rust` you could open another issue.

WDYT?
