### ISSUE TITLE
UriValidator assumes UURis always contain logical names

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/up-rust#78]
The `validate*` functions of `UriValidator` seem to assume that a UUri always contains *at least* the logical names of authorities, entities, resources.

This means that the following code fails:
```rust
// up://10.0.5.101/24576/1/256
let uri = UUri {
    authority: Some(UAuthority {
        number: Some(Number::Ip(vec![10, 0, 5, 101])),
        ..Default::default()
    })
    .into(),
    entity: Some(UEntity {
        id: Some(24576),
        version_major: Some(1),
        ..Default::default()
    })
    .into(),
    resource: Some(UResource {
        id: Some(256),
        ..Default::default()
    })
    .into(),
    ..Default::default()
};
assert!(
    UriValidator::validate(&uri).is_ok(),
    "UUris that contain only identifiers (no logical names) should validate successfully"
);
```

This is a problem in situations where you want to use `UMessageBuilder` with a UUri that only contains identifiers, e.g. when interacting with services via SOME/IP. The bulder will not be able to create the message in this case because the `build` function invokes `UriValidator::validate` for the message's source/sink.

The same problem occurs with the other validator functions.
IMHO all functions should to be adapted to check on logical names but to also accept identifiers, if no logical name is set.

**Comment by PLeVasseur** [comment]
Good point.

So the idea would be to set the bar at a minimum to the fields required for Micro Form (i.e. the identifiers)?

I seem to recall there was an issue pointing something like this out on up-spec, but I can't seem to find it at the moment.

**Comment by PLeVasseur** [comment]
Is this relevant still?

**Comment by sophokles73** [comment]
UUri has been changed to only contain a (potentially empty) authority _name_ but no longer supports an identifier nor byte array (IP address).
