### ISSUE TITLE
Adding short-form UUri

### ISSUE THREAD

**Issue by evshary** [eclipse-uprotocol/up-rust#80]
Now the short-form UUri is back in https://github.com/eclipse-uprotocol/up-spec/pull/89, should we add the short-form UUri in up-rust?
It might be easier to transform the UUri into MQTT topic or Zenoh key if we have short-form UUri, but still need to sync with other languages to ensure interoperability.

**Comment by PLeVasseur** [comment]
A good point! We need to add support for Short form for compliance with 1.5.8

**Comment by PLeVasseur** [comment]
Maybe good to also add `v1.5.8` tag on here @stevenhartley

**Comment by stevenhartley** [comment]
> Maybe good to also add `v1.5.8` tag on here @stevenhartley

the tag is in the up-spec project. You guys can add the tags to the other projects if you like.

**Comment by sophokles73** [comment]
Before we start implementing this, I'd like to first clarify what kind of UUris we actually want to be able to [serialize to short form](https://github.com/eclipse-uprotocol/up-spec/pull/121#discussion_r1575819800), in particular in the context of wildcard usage in UUris ...

**Comment by PLeVasseur** [comment]
A [relevant comment](https://github.com/eclipse-uprotocol/up-cpp/pull/99/files#r1581196402) over on the `up-cpp` API redesign I made:
> Interesting question 🤔
> 
> Over in `up-rust`, we completely dismantled the idea of having separate serializers and deserializers.
> 
> We instead leaned on the Rust trait `TryFrom` and `impl`ed that on the `UUri` struct to allow going:
> 
> * `UUri` -> `String`, `String` -> `UUri` (i.e. long form) and
> * `UUri` -> `Vec<u8>`, `Vec<u8>` -> `UUri` (i.e. micro form)
> 
> **which, thinking about it now, is a bit of a fumble, since both Long Form and Short Form are `String`s, so we'll need to revisit this**

**Comment by sophokles73** [comment]
This is obsolete with https://github.com/eclipse-uprotocol/up-spec/pull/126 and https://github.com/eclipse-uprotocol/up-spec/pull/121
