### ISSUE TITLE
`uSubscription` as a trait in support of pluggable uStreamer

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-rust#82]
As @stevenhartley has found by experimenting on uStreamer, it looks like it will make it easier to have a `uSubscription` trait.

Why?

Because `up-streamer-rust` (which is generic and should be able to work with any transports) will need to interact with not a concrete implementation of a `uSubscription`, but in fact some generic representation of one, because there will be different `uSubscription` implementations per transport.

Tagging in @AnotherDaniel & @sophokles73 for discussion

**Comment by AnotherDaniel** [comment]
Hm, going by the implementation in your fork, this does not look horrible ;-)

I am only just getting off the ground with my usubscription component, managed a little 'breakthrough' (by my standards) yesterday, so slowly there emerges a scaffold to hang things on... at the moment I can say this:

 - I'm also trying to make usubscription transport-agnostic (-pluggable), although not 100% there yet to have a full opinion
 - being immersed in the usage side of up-rust and all the rest now, I've started some background tasks in my mind wrt how to make this more usable going forward; I haven't gotten as far as you guys yet, but a up-subscription trait that serves as the frond-end for client code interactions fits some of these thoughts (at least I think so at the moment)
 
Again, I'm late to the party of actually working with all this - so the coming weeks will be needed on my side to flesh out how I feel about all of this. 
Right now I'd say let's try this out, let's have the trait - if it needs to change then it can, if we really hate it, or it really should live somewhere else, then we also can address that going forward.

**Comment by PLeVasseur** [comment]
Okay, so based on your feedback, does it make sense for me to add doc comments to the branch for https://github.com/PLeVasseur/uprotocol-rust_fork/pull/1 and open a PR into `up-rust` as a first step?

**Comment by AnotherDaniel** [comment]
Yupp that's what I'd suggest. If the PR is ok for @sophokles73 , then I can immediately also use this in my up-subscription code base, see what it does for me.

**Comment by PLeVasseur** [comment]
Alrighty -- if you're good with me taking a try at it, I'll refine this a bit, add some doc comments and doc tests and then retarget it for `up-rust`. :+1:

**Comment by PLeVasseur** [comment]
Took a shot at this in #83
