### ISSUE TITLE
Serialize/Deserialize - UMessage, UAttribute, UURI etc.

### ISSUE THREAD

**Issue by sagarsshah** [eclipse-uprotocol/up-rust#99]
We have bunch deserialization functions in this file. it is used for convering json message to proto messages.   will this be worth having it in up-rust?
https://github.com/sagarsshah/up-tck/blob/main/test_agent/rust/src/utils.rs

**Comment by sophokles73** [comment]
Maybe you can provide a little context regarding the use case that this functionality would be helpful in?

**Comment by PLeVasseur** [comment]
@sagarsshah -- any further motivation you can provide?
